CREATE DATABASE IF NOT EXISTS Encuesta;
USE Encuesta;

CREATE TABLE `eleccion` (
  `ID_ELECCION` int(11) NOT NULL AUTO_INCREMENT,
  `DESC_ELECCION` varchar(100) COLLATE utf8_spanish2_ci NOT NULL,
  PRIMARY KEY (`ID_ELECCION`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;


CREATE TABLE `persona` (
  `ID_PERSONA` int(11) NOT NULL AUTO_INCREMENT,
  `ID_ELECCION` int(11) NOT NULL,
  `NOMBRES` varchar(80) COLLATE utf8_spanish2_ci NOT NULL,
  `APELLIDOS` varchar(100) COLLATE utf8_spanish2_ci NOT NULL,
  `EDAD` int(11) NOT NULL,
  PRIMARY KEY (`ID_PERSONA`),
  KEY `ID_ELECCION` (`ID_ELECCION`),
  CONSTRAINT `PERSONA_FK1` FOREIGN KEY (`ID_ELECCION`) REFERENCES `eleccion` (`ID_ELECCION`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;